### ISSUE TITLE
Unable to start supbox

### ISSUE THREAD

**Issue by om2amr** [gabek/supbox#7]
Hi,

I'm using Rekordbox 6.6. Just found your great app and tried it. But unfortunately it would not start:

```
./supbox 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getEncryptedPassword(0xc000062310, 0x65, 0x58, 0xc00001e280)
	/Users/gabek/src/supbox/utils.go:65 +0x1e4
main.main()
	/Users/gabek/src/supbox/main.go:27 +0x238
```

Any idea what I'm doing wrong please ?  It seems it is not able to find db password.

Thank you in advance !

Radim

**Comment by gabek** [comment]
I wonder if Rekordbox made changes around the password to break tools like this. Unfortunately I haven't been actively maintaining this since I haven't been using it myself. I know Triode is working on "Now Playing", it might be a better bet to give that tool a spin: https://www.nowplaying2.com/

**Comment by om2amr** [comment]
Hello Gabe,

I appreciate you answered to the question to your older project. I know about Triode nowplaying, it is great tool too, but not for Pioneer console in MIDI mode unfortunately. I’m using similar project like your is - unbox. The only thing I’m missing is Artwork. 

So take it easy, I can live without it :-)

Cheers,

Radim
